# Generated by Django 5.0.7 on 2024-08-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_licitacaoquantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicitacaoValoresMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('valor_total', models.FloatField()),
            ],
        ),
    ]
