name: Script de automação dos envio de emails

on:
  workflow_dispatch:
  schedule:
    - cron: '00 15 * * 1' # todos as segunda-feiras às 12:00

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
        cd backend/newsletter
        npm install

    - name: Run Script
      working-directory: backend/newsletter
      env:
        URL_CHIMP: ${{ env.URL_CHIMP }}
        API: ${{ env.API }}
        GMAIL_USER: ${{ env.GMAIL_USER }}
        GMAIL_PASS: ${{ env.GMAIL_PASS }}
      run: |
        node sendEmails.js
